from app.schemas import ProjectMemory
from app.services.storage_service import ProjectStorageService

class MarkdownGeneratorService:
    def __init__(self, storage_service: ProjectStorageService):
        self.storage_service = storage_service

    async def generate_all_markdowns(self, project: ProjectMemory):
        await self.generate_readme(project)
        await self.generate_project_spec(project)
        await self.generate_architecture(project)
        await self.generate_roadmap(project)
        await self.generate_tasks(project)
        await self.generate_api_docs(project)
        await self.generate_deployment(project)
        await self.generate_changelog(project)

    async def generate_readme(self, project: ProjectMemory):
        content = f"# {project.project_name}\n\n"
        content += f"Framework: {project.framework}\n"
        content += f"Architecture: {project.architecture}\n\n"
        content += "## Overview\nThis project was generated by Band.ai Orchestrator.\n"
        await self.storage_service.write_file(project.project_id, "README.md", content)

    async def generate_project_spec(self, project: ProjectMemory):
        content = f"# Project Specification: {project.project_name}\n\n"
        content += "## Requirements\n- Auto-generated specification document.\n"
        await self.storage_service.write_file(project.project_id, "PROJECT_SPEC.md", content)

    async def generate_architecture(self, project: ProjectMemory):
        content = f"# Architecture: {project.project_name}\n\n"
        content += f"## Style: {project.architecture}\n"
        await self.storage_service.write_file(project.project_id, "ARCHITECTURE.md", content)

    async def generate_roadmap(self, project: ProjectMemory):
        content = f"# Roadmap\n\n- Define initial goals\n"
        await self.storage_service.write_file(project.project_id, "ROADMAP.md", content)

    async def generate_tasks(self, project: ProjectMemory):
        content = f"# Tasks\n\n"
        content += "## Pending\n"
        for t in project.pending_tasks:
            content += f"- [ ] {t}\n"
        content += "\n## Completed\n"
        for t in project.completed_tasks:
            content += f"- [x] {t}\n"
        await self.storage_service.write_file(project.project_id, "TASKS.md", content)

    async def generate_api_docs(self, project: ProjectMemory):
        content = f"# API Documentation\n\nTo be generated by Engineer Agent.\n"
        await self.storage_service.write_file(project.project_id, "API_DOCS.md", content)

    async def generate_deployment(self, project: ProjectMemory):
        content = f"# Deployment Guide\n\nTo be generated by Planner Agent.\n"
        await self.storage_service.write_file(project.project_id, "DEPLOYMENT.md", content)

    async def generate_changelog(self, project: ProjectMemory):
        content = f"# Changelog\n\n## Initial Setup\n- Project initialized.\n"
        await self.storage_service.write_file(project.project_id, "CHANGELOG.md", content)
